FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
COPY .npmrc ./

RUN npm ci --no-audit --no-fund

EXPOSE 3001
ENV NEXT_TELEMETRY_DISABLED=1

CMD ["sh","-lc","if [ ! -d node_modules ] || [ -z \"$(ls -A node_modules 2>/dev/null)\" ]; then npm ci --no-audit --no-fund; fi; npm run dev -- -p 3001 -H 0.0.0.0"]
