from __future__ import annotations

import html
import re
from html.parser import HTMLParser
from typing import Dict, List

from sasb_ocr_extractor.utils.text import SASB_ANY_CODE_RE, clean_text, normalise_header


class _HtmlTableExtractor(HTMLParser):
    def __init__(self):
        super().__init__(convert_charrefs=True)
        self.tables: List[List[List[str]]] = []
        self._in_table = False
        self._in_row = False
        self._in_cell = False
        self._current_table: List[List[str]] = []
        self._current_row: List[str] = []
        self._current_cell: List[str] = []

    def handle_starttag(self, tag, attrs):
        tag = tag.lower()
        if tag == "table":
            self._in_table = True
            self._current_table = []
        elif self._in_table and tag == "tr":
            self._in_row = True
            self._current_row = []
        elif self._in_row and tag in {"td", "th"}:
            self._in_cell = True
            self._current_cell = []

    def handle_endtag(self, tag):
        tag = tag.lower()
        if tag in {"td", "th"} and self._in_cell:
            self._current_row.append("".join(self._current_cell))
            self._current_cell = []
            self._in_cell = False
        elif tag == "tr" and self._in_row:
            if self._current_row:
                self._current_table.append(self._current_row)
            self._current_row = []
            self._in_row = False
        elif tag == "table" and self._in_table:
            if self._current_table:
                self.tables.append(self._current_table)
            self._current_table = []
            self._in_table = False
            self._in_row = False
            self._in_cell = False

    def handle_data(self, data):
        if self._in_cell:
            self._current_cell.append(data)


class SasbTableParser:
    """Parse OCR/Markdown table blocks into raw row dictionaries.

    Prefer structured tables generated by PaddleOCR-VL. If no clean table exists,
    use a best-effort line parser keyed by SASB codes.
    """

    def parse(self, section_text: str, section_type: str) -> List[Dict[str, str]]:
        rows = self._parse_html_tables(section_text, section_type)
        if not rows:
            rows = self._parse_markdown_tables(section_text)
        if not rows:
            rows = self._parse_line_based(section_text)
        for row in rows:
            row["Type"] = section_type
        return rows

    def _parse_html_tables(self, text: str, section_type: str) -> List[Dict[str, str]]:
        if "<table" not in text.lower():
            return []
        parser = _HtmlTableExtractor()
        try:
            parser.feed(text)
        except Exception:
            return []

        all_rows: List[Dict[str, str]] = []
        for table in parser.tables:
            if not table:
                continue
            rows = self._rows_from_html_table(table, section_type)
            if rows:
                all_rows.extend(rows)
        return all_rows

    def _rows_from_html_table(self, table: List[List[str]], section_type: str) -> List[Dict[str, str]]:
        header_idx = None
        header_norm: List[str] = []
        for idx, row in enumerate(table):
            cells = [self._clean_cell(c) for c in row]
            hnorm = [normalise_header(c) for c in cells]
            joined = " ".join(hnorm)
            if "code" not in joined:
                continue
            if section_type == "Activity Metrics":
                if "activity" in joined and "metric" in joined:
                    header_idx = idx
                    header_norm = hnorm
                    break
            elif "topic" in joined and "metric" in joined:
                header_idx = idx
                header_norm = hnorm
                break
        if header_idx is None:
            return []

        rows: List[Dict[str, str]] = []
        current_topic = ""
        for raw_row in table[header_idx + 1:]:
            cells = [self._clean_cell(c) for c in raw_row]
            cells = [c for c in cells if c]
            if not cells:
                continue
            joined = " ".join(cells)
            code_match = SASB_ANY_CODE_RE.search(joined)
            if not code_match:
                continue
            code = code_match.group(0)

            if section_type == "Activity Metrics":
                row = self._activity_row_from_cells(cells, code)
            else:
                row = self._disclosure_row_from_cells(cells, code, current_topic)
                if row.get("Topic"):
                    current_topic = row["Topic"]
            if row.get("Metric"):
                rows.append(row)
        return rows

    def _disclosure_row_from_cells(self, cells: List[str], code: str, current_topic: str) -> Dict[str, str]:
        code_idx = self._cell_index_containing_code(cells, code)
        before_code = cells[:code_idx] if code_idx is not None else cells[:-1]
        before_code = [self._strip_code(c, code) for c in before_code]
        before_code = [c for c in before_code if c]

        topic = current_topic
        metric = ""
        category = ""
        unit = ""

        if len(before_code) >= 4:
            topic, metric, category, unit = before_code[0], before_code[1], before_code[2], before_code[3]
        elif len(before_code) == 3:
            metric, category, unit = before_code
        elif len(before_code) == 2:
            metric, category = before_code
        elif len(before_code) == 1:
            metric = before_code[0]

        return {
            "Topic": self._clean_cell(topic),
            "Metric": self._clean_metric(metric),
            "Category": self._clean_cell(category),
            "Unit": self._clean_cell(unit),
            "Code": code,
        }

    def _activity_row_from_cells(self, cells: List[str], code: str) -> Dict[str, str]:
        code_idx = self._cell_index_containing_code(cells, code)
        before_code = cells[:code_idx] if code_idx is not None else cells[:-1]
        before_code = [self._strip_code(c, code) for c in before_code]
        before_code = [c for c in before_code if c]

        metric = ""
        category = ""
        unit = ""
        if len(before_code) >= 3:
            metric, category, unit = before_code[0], before_code[1], before_code[2]
        elif len(before_code) == 2:
            metric, category = before_code
        elif len(before_code) == 1:
            metric = before_code[0]

        return {
            "Topic": "",
            "Metric": self._clean_metric(metric),
            "Category": self._clean_cell(category),
            "Unit": self._clean_cell(unit),
            "Code": code,
        }

    def _cell_index_containing_code(self, cells: List[str], code: str) -> int | None:
        for idx, cell in enumerate(cells):
            if code in cell:
                return idx
        return None

    def _strip_code(self, text: str, code: str) -> str:
        return clean_text(str(text or "").replace(code, ""))

    def _normalise_latex_tokens(self, text: str) -> str:
        replacements = [
            (r"\$\s*CO_\{2\}-e\s*\$", "CO₂-e"),
            (r"\$\s*CO_\{2\}\s*\$", "CO₂"),
            (r"\$\s*gCO\s*\$?\s*_\{2\}\s*\$?", "gCO₂"),
            (r"\$\s*NO_\{x\}\s*\$", "NOx"),
            (r"\$\s*N_\{2\}O\s*\$", "N2O"),
            (r"\$\s*SO_\{x\}\s*\$", "SOx"),
            (r"\$\s*PM_\{10\}\s*\$", "PM10"),
            (r"\$\s*m\^\{2\}\s*\$", "m²"),
            (r"\$\s*m\^\{3\}\s*\$", "m³"),
        ]
        value = str(text or "")
        for pattern, replacement in replacements:
            value = re.sub(pattern, replacement, value, flags=re.I)
        return value

    def _clean_cell(self, text: object) -> str:
        value = html.unescape(str(text or ""))
        value = re.sub(r"<[^>]+>", " ", value)
        value = self._normalise_latex_tokens(value)
        value = re.sub(r"\$\s*(?:\{\}\s*)?\^\s*\{?\d+[A-Za-z,]*\}?\s*\$", " ", value)
        value = re.sub(r"\s+([,.;:])", r"\1", value)
        return clean_text(value)

    def _clean_metric(self, text: object) -> str:
        value = self._clean_cell(text)
        value = re.sub(r"\s*,\s*$", "", value)
        return clean_text(value)

    def _parse_markdown_tables(self, text: str) -> List[Dict[str, str]]:
        lines = [line.strip() for line in clean_text(text).splitlines() if line.strip()]
        pipe_lines = [line for line in lines if "|" in line]
        if not pipe_lines:
            return []

        header_idx = None
        headers: List[str] = []
        for idx, line in enumerate(pipe_lines):
            raw_cells = [self._clean_cell(c) for c in line.strip("|").split("|")]
            hnorm = [normalise_header(c) for c in raw_cells]
            if any("topic" == h for h in hnorm) and any("metric" == h for h in hnorm) and any("code" == h for h in hnorm):
                header_idx = idx
                headers = hnorm
                break
            joined = " ".join(hnorm)
            if "topic" in joined and "metric" in joined and "category" in joined and "code" in joined:
                header_idx = idx
                headers = hnorm
                break

        if header_idx is None:
            return []

        # Map common headers to canonical fields.
        def field_for_header(h: str) -> str:
            if h == "topic" or h == "activity metric" or h == "activity":
                return "Topic"
            if h == "metric" or h.endswith(" metric"):
                return "Metric"
            if h == "category":
                return "Category"
            if "unit" in h:
                return "Unit"
            if h == "code":
                return "Code"
            return h

        fields = [field_for_header(h) for h in headers]
        rows: List[Dict[str, str]] = []
        current_topic = ""

        for line in pipe_lines[header_idx + 1:]:
            if re.search(r"\|?\s*:?-{3,}:?\s*\|", line):
                continue
            cells = [self._clean_cell(c) for c in line.strip("|").split("|")]
            if len(cells) < 2:
                continue
            row = {"Topic": "", "Metric": "", "Category": "", "Unit": "", "Code": ""}
            for i, cell in enumerate(cells):
                if i < len(fields) and fields[i] in row:
                    row[fields[i]] = cell
            if not row["Code"]:
                code_match = SASB_ANY_CODE_RE.search(" ".join(cells))
                if code_match:
                    row["Code"] = code_match.group(0)
            code_match = SASB_ANY_CODE_RE.search(row["Code"])
            if not code_match:
                continue
            row["Code"] = code_match.group(0)
            row["Metric"] = self._clean_metric(row["Metric"])
            row["Unit"] = self._clean_cell(row["Unit"])
            row["Category"] = self._clean_cell(row["Category"])
            if row["Topic"]:
                current_topic = row["Topic"]
            else:
                row["Topic"] = current_topic
            rows.append(row)
        return rows

    def _parse_line_based(self, text: str) -> List[Dict[str, str]]:
        value = clean_text(text)
        matches = list(SASB_ANY_CODE_RE.finditer(value))
        rows: List[Dict[str, str]] = []
        if not matches:
            return rows

        current_topic = ""
        for idx, match in enumerate(matches):
            code = match.group(0)
            prev_end = matches[idx - 1].end() if idx > 0 else 0
            row_text = clean_text(value[prev_end: match.start()])
            row_text = self._strip_table_noise(row_text)
            if not row_text:
                continue

            category = self._find_category(row_text)
            if not category:
                continue

            cat_pattern = r"\s+".join(re.escape(x) for x in category.split())
            split_parts = re.split(cat_pattern, row_text, maxsplit=1, flags=re.I)
            if len(split_parts) != 2:
                continue
            before_cat, after_cat = split_parts
            unit = self._clean_cell(after_cat)
            metric_and_topic = self._clean_cell(before_cat)

            topic, metric = self._split_topic_metric(metric_and_topic, current_topic)
            if topic:
                current_topic = topic
            if not metric:
                continue

            rows.append({
                "Topic": self._clean_cell(current_topic),
                "Metric": self._clean_metric(metric),
                "Category": category,
                "Unit": unit,
                "Code": code,
            })
        return rows

    def _strip_table_noise(self, text: str) -> str:
        text = html.unescape(str(text or ""))
        text = re.sub(r"<[^>]+>", " ", text)
        text = re.sub(r"(?i)SUSTAINABILITY DISCLOSURE TOPICS & METRICS", " ", text)
        text = re.sub(r"(?i)Table\s+[12]\.\s*(Sustainability Disclosure Topics & Metrics|Activity Metrics)?", " ", text)
        text = re.sub(r"(?i)TOPIC\s+METRIC\s+CATEGORY\s+UNIT\s+OF\s+MEASURE\s+CODE", " ", text)
        text = re.sub(r"(?i)ACTIVITY\s+METRIC\s+CATEGORY\s+UNIT\s+OF\s+MEASURE\s+CODE", " ", text)
        return clean_text(text)

    def _find_category(self, row_text: str) -> str:
        if re.search(r"Discussion\s+and\s+Analysis", row_text, flags=re.I):
            return "Discussion and Analysis"
        if re.search(r"\bQuantitative\b", row_text, flags=re.I):
            return "Quantitative"
        return ""

    def _split_topic_metric(self, text: str, current_topic: str) -> tuple[str, str]:
        starts = [
            r"Discussion\b", r"Description\b", r"Percentage\b", r"Total\b",
            r"Number\b", r"Amount\b", r"Annual\b", r"Area\b", r"Direct\b",
            r"\(1\)", r"List\b", r"Weight\b", r"Gross\b", r"Fleet\b",
            r"Revenue\b",
        ]
        m = re.search("|".join(starts), text, flags=re.I)
        if m and m.start() > 0:
            return clean_text(text[: m.start()]), clean_text(text[m.start():])
        return current_topic, clean_text(text)
