import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@/lib/antd";
// import { StagewiseToolbar } from "@stagewise/toolbar-next"; // 临时注释：如需启用工具条，解除本行和下方块注释


export const metadata: Metadata = {
  title: "Euler ESG",
  description: "Generated by create next app",
  icons: {
    icon: "/Euler-Img.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="zh-CN" className="overflow-x-hidden" suppressHydrationWarning>
      <body className="antialiased overflow-x-hidden">
        <AntdRegistry>
          <div id="root-layout">{children}</div>
        </AntdRegistry>
        {/* 如需使用 Stagewise 工具条，取消下方注释 */}
        {/* {process.env.NODE_ENV === "development" && (
          <StagewiseToolbar config={{ plugins: [] }} />
        )} */}
      </body>
    </html>
  );
}
